import type { DocumentTypeCode } from "nationid";

/**
 * Realistic-looking sample inputs that pass each spec's check digit.
 *
 * These are NOT real people's documents — they were generated by hand or by
 * running the validator against synthetic candidates until check digits match.
 * Used as one-click "Try a sample" affordances in the playground.
 *
 * Pinned to `nationid@0.3.0`. New v0.4 codes (BO_CI, EC_CEDULA, …) can be
 * added incrementally as the library publishes them.
 */
export const SAMPLE_INPUTS: Partial<Record<DocumentTypeCode, string>> = {
  SV_DUI: "04567890-3",
  SV_NIT: "06141505851012",
  MX_CURP: "GOMC850315HDFRRR07",
  MX_RFC_PF: "VECJ880326XXX",
  MX_RFC_PM: "ABC123456T1A",
  CO_CC: "1020304050",
  CO_NIT: "900123456-7",
  BR_CPF: "390.533.447-05",
  BR_CNPJ: "11.222.333/0001-81",
  PE_DNI: "12345678",
  PE_RUC: "20131312955",
  AR_DNI: "12345678",
  AR_CUIT: "30-12345678-1",
  AR_CUIL: "20-12345678-3",
  CL_RUT: "11.111.111-1",
  DO_CEDULA: "001-1234567-8",
  GT_DPI: "1234 56789 0101",
  GT_NIT: "1234567-8",
  HN_DNI: "0801-1990-12345",
  CR_CEDULA_FISICA: "1-1234-5678",
  ES_DNI: "12345678Z",
  ES_NIE: "X1234567L",
  US_SSN: "123-45-6789",
  US_EIN: "12-3456789",
};

export function getSample(code: DocumentTypeCode): string | undefined {
  return SAMPLE_INPUTS[code];
}
